spring:
    application:
        name: AQM

server:
    port: ${SERVICE_PORT:8008}
    context-path: /${CONTEXT_PATH:}

cxf:
    servlet:
        init:
            service-list-path: /info
    jaxrs:
        component-scan: true
        client:
            address: http://localhost:${server.port}
            classes-scan-packages: com.khalichi


logging:
    level:
        com:
            khalichi: debug

swagger:
    feature:
        base-path: /services
        title: Air Traffic Control (ATC) Queue Management (AQM)
        description: https://github.com/kkhalichi/aqm
        contact: Keivan Khalichi (keivan@khalichi.com)
        license: Copyright (c) 2017 Khalichi.com
        license-url: https://raw.githubusercontent.com/kkhalichi/aqm/master/LICENSE
        version: 1.0-SNAPSHOT
        pretty-print: true